### ISSUE TITLE
Create Singleplayer

### ISSUE THREAD

**Issue by sebastianchengg** [TormodNy/pockball#1]
The overall issue for Singleplayer. Have ordered the tasks from what makes sense to implement first till last from top to bottom
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #20

**Comment by thuthao-jennifer** [comment]
All done except for creating tests, which we will not do
